[package]
name = "markdown"
edition.workspace = true
rust-version.workspace = true

[lib]
path = "utils.rs"

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
validator.workspace = true
