load(":python.bzl", "py_source")

py_source(
    name = "black_test",
    src = "black_test.py",
    visibility = ["//visibility:public"],
)

py_source(
    name = "flake8_test",
    src = "flake8_test.py",
    visibility = ["//visibility:public"],
)

py_source(
    name = "mypy_test",
    src = "mypy_test.py",
    visibility = ["//visibility:public"],
)
