[tool.black]
line-length = 100

[tool.pylint.MASTER]
ignore-patterns = ".*.pyi"
persistent = "no"

[tool.pylint.'MESSAGES CONTROL']
disable = "invalid-name,missing-docstring,too-few-public-methods,too-many-public-methods,too-many-locals,too-many-lines,too-many-arguments,too-many-statements,too-many-branches,consider-using-f-string,unknown-option-value"
enable = "unused-argument"

[tool.pylint.VARIABLES]
dummy-variables-rgx = "_.*"

[tool.pylint.REPORTS]
output-format = "parseable"
score = "no"
