FROM ubuntu:22.04

ENV TZ UTC

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y \
    catdoc \
    gcc \
    git \
    python3 \
    texlive-full \
    unzip \
    wget \
    xz-utils && \
    rm -rf /var/lib/apt/lists/*

ARG uid
ARG gid

RUN addgroup --gid ${gid} markdown && \
    adduser --uid ${uid} --gid ${gid} markdown

RUN mkdir /nix && \
    chown ${uid}:${gid} /nix

USER ${uid}:${gid}
ENV USER markdown
WORKDIR /home/markdown

RUN wget https://releases.nixos.org/nix/nix-2.24.4/install && \
    chmod a+x install && \
    ./install --yes --no-daemon && \
    rm install && \
    mkdir -p .config/nix && \
    echo 'experimental-features = nix-command flakes' > .config/nix/nix.conf

ARG nixpkgs_commit

RUN bash -l -c "nix profile install nixpkgs/${nixpkgs_commit}#bazelisk" && \
    mkdir bin && \
    ln -s ~/.nix-profile/bin/bazelisk bin/bazel && \
    echo 'export PATH="${HOME}/bin:${PATH}"' >> .profile

COPY --chown=${uid}:${gid} . /home/markdown/markdown-makefile

RUN export GIT_AUTHOR_NAME='test' && \
    export GIT_COMMITTER_NAME='test' &&\
    export GIT_AUTHOR_EMAIL='test@example.com' && \
    export GIT_COMMITTER_EMAIL='test@example.com' && \
    ( \
    cd markdown-makefile && \
    git -c init.defaultBranch=main init . && \
    git add --all && \
    git commit --quiet -m 'Test' \
    ) && \
    cp -a markdown-makefile/tests/other_workspace other-workspace-unversioned && \
    rm other-workspace-unversioned/.gitignore && \
    sed -i 's|path = "../.."|path = "../markdown-makefile"|g' other-workspace-unversioned/MODULE.bazel && \
    sed -i 's|versioned_test|unversioned_test|g' other-workspace-unversioned/tests/test6/BUILD && \
    cp markdown-makefile/markdown/private/git/run_tests .

RUN cd markdown-makefile && \
    bash -l -c "bazel run :git_update" && \
    bash -l -c "bazel clean" && \
    rm -rf ~/.cache/bazel ~/.cache/bazelisk

ENTRYPOINT ["bash", "-l"]
