load("@markdown//:defs.bzl", "md_group", "md_workspace")

md_workspace()

md_group(
    name = "tests",
    deps = [
        "//tests/test1",
        "//tests/test2",
        "//tests/test3",
        "//tests/test4",
        "//tests/test5",
        "//tests/test6",
    ],
)
