import io
from collections.abc import Mapping, Sequence
from typing import Any

class Element:
    content: Sequence[Element]

class Block(Element): ...
class Inline(Element): ...
class MetaValue(Element): ...

class Doc(Element):
    metadata: Mapping[str, MetaValue]
    def get_metadata(self) -> Mapping[str, Any]: ...

class BlockQuote(Block):
    def __init__(self, *args: Block) -> None: ...

class BulletList(Block):
    def __init__(self, *args: ListItem) -> None: ...

class Caption(Element):
    def __init__(self, args: Block) -> None: ...

class CodeBlock(Block):
    def __init__(self, text: str) -> None: ...

class Definition(Element):
    def __init__(self, *args: Block) -> None: ...

class DefinitionItem(Element):
    def __init__(self, term: list[Inline], definitions: list[Definition]) -> None: ...

class DefinitionList(Block):
    def __init__(self, *args: DefinitionItem) -> None: ...

class Div(Block):
    def __init__(self, *args: Block, classes: Sequence[str]) -> None: ...

class Figure(Block):
    def __init__(self, args: Block, caption: Caption | None = None) -> None: ...

class Header(Block):
    def __init__(self, *args: Inline, level: int, identifier: str = "") -> None: ...

class HorizontalRule(Block):
    def __init__(self) -> None: ...

class Image(Inline):
    def __init__(self, *args: Inline, url: str = "", title: str = "") -> None: ...

class LineBlock(Block):
    def __init__(self, *args: LineItem) -> None: ...

class LineItem(Element):
    def __init__(self, *args: Inline) -> None: ...

class Link(Inline):
    def __init__(self, *args: Inline, title: str = "") -> None: ...

class ListItem(Element):
    def __init__(self, *args: Block) -> None: ...

class MetaInlines(MetaValue):
    def __init__(self, *args: Inline) -> None: ...

class MetaString(MetaValue):
    def __init__(self, text: str) -> None: ...

class Note(Inline):
    def __init__(self, *args: Block) -> None: ...

class OrderedList(Block):
    def __init__(self, *args: ListItem) -> None: ...

class Para(Block):
    def __init__(self, *args: Inline) -> None: ...

class Plain(Block):
    def __init__(self, *args: Inline) -> None: ...

class Space(Inline): ...

class Span(Inline):
    def __init__(self, *args: Inline, classes: Sequence[str]) -> None: ...

class Str(Inline):
    def __init__(self, text: str) -> None: ...

def load(input_stream: io.TextIOBase | None = None) -> Doc: ...
def dump(doc: Doc, output_stream: io.TextIOBase | None = None) -> None: ...
