load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "//markdown/collection:defs_bzl",
        "//markdown/core:defs_bzl",
        "//markdown/dynamic_group:defs_bzl",
        "//markdown/formats:defs_bzl",
        "//markdown/git:defs_bzl",
        "//markdown/group:defs_bzl",
        "//markdown/workspace:defs_bzl",
    ],
)
