load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("//markdown/support/shell:defs.bzl", "sh_source", "sh_test")

bzl_library(
    name = "defs_bzl",
    srcs = ["defs.bzl"],
    visibility = ["//markdown/private:__pkg__"],
    deps = ["//markdown/summary:defs_bzl"],
)

exports_files(
    [
        "bazelversion",
        "bazelrc",
    ],
    visibility = ["//visibility:public"],
)

sh_source(
    name = "new_package",
    src = "new_package.sh",
    visibility = ["//visibility:public"],
)

sh_test(
    name = "new_package_test",
    srcs = ["new_package_test.sh"],
    args = ["$(rootpath new_package.sh)"],
    data = ["new_package.sh"],
)

sh_source(
    name = "workspace_status",
    src = "workspace_status",
    visibility = ["//visibility:public"],
)

sh_test(
    name = "workspace_status_test",
    srcs = ["workspace_status_test.sh"],
    args = [
        "$(rootpath workspace_status)",
        "$(rootpath //markdown/utils:git_repo_version)",
    ],
    data = [
        "workspace_status",
        "//markdown/utils:git_repo_version",
    ],
)
