alias(
    name = "ebook_convert",
    actual = "@calibre//:ebook_convert",
    visibility = ["//:__subpackages__"],
)

alias(
    name = "pandoc",
    actual = "@pandoc//:pandoc",
    visibility = ["//:__subpackages__"],
)
